**1.0 Introdução**

Código com finalidade de extrair dados referente ao cartola FC. 

detalhes da extração está disponível em: 

https://dadosaocubo.com/extrair-dados-da-api-do-cartola-fc/

**2.0 Pacotes**

In [16]:
# %pip install pandas
# %pip install requests

In [17]:
import pandas as pd
import requests
import json
import warnings
warnings.filterwarnings("ignore")

**3.0 Dados**

Obter e baixar dados

**3.1 Pontuações**

Obter pontuações dos jogadores nas rodadas

In [18]:
#funcao que obtem dado de acordo com a rodada (input)
def GetPontuacao(rodada):
 url = 'https://api.cartola.globo.com/atletas/pontuados/'+str(rodada)
 resposta = requests.get(url)
 data = resposta.json()
 df = pd.DataFrame(data)
 #Normaliza a coluna "atletas" e cria um novo DataFrame
 df = pd.json_normalize(df['atletas'])
 #Remove o prefixo "scout." das colunas
 df.rename(columns=lambda x: x.replace('scout.', ''), inplace=True)
 df['rodada'] = rodada
 
 return df

In [19]:
#primeira execucao
rodadas = 1
print("Finalizado rodada:",str(rodadas)+ "...")
df1= GetPontuacao(1)

#loop para gerar dados, até ultima rodada.
while rodadas != "Erro":
 try:
  rodadas = rodadas+1
  df= GetPontuacao(rodadas)
  df1 = df.append(df1)
  print("Finalizado rodada:",str(rodadas)+ "...")
  
 except:
  rodadas = "Erro"
  print("Fim")

Finalizado rodada: 1...

Finalizado rodada: 2...
Finalizado rodada: 3...
Finalizado rodada: 4...
Finalizado rodada: 5...
Finalizado rodada: 6...
Finalizado rodada: 7...
Finalizado rodada: 8...
Finalizado rodada: 9...
Finalizado rodada: 10...
Finalizado rodada: 11...
Finalizado rodada: 12...
Finalizado rodada: 13...
Finalizado rodada: 14...
Finalizado rodada: 15...
Finalizado rodada: 16...
Finalizado rodada: 17...
Finalizado rodada: 18...
Finalizado rodada: 19...
Finalizado rodada: 20...
Finalizado rodada: 21...
Finalizado rodada: 22...
Finalizado rodada: 23...
Finalizado rodada: 24...
Finalizado rodada: 25...
Finalizado rodada: 26...
Finalizado rodada: 27...
Finalizado rodada: 28...
Finalizado rodada: 29...
Finalizado rodada: 30...
Finalizado rodada: 31...
Finalizado rodada: 32...
Finalizado rodada: 33...
Fim

In [20]:
#visualizar dados gerados
display(df1.head(5))

,apelido,foto,pontuacao,posicao_id,clube_id,entrou_em_campo,DS,FC,FS,FF,...,GS,FT,CV,PC,V,scout,rodada,DP,PP,GC
0,Zaracho,https://s.sde.globo.com/media/person_role/2023...,3.2,4.0,282.0,True,3.0,3.0,1.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,33,NaN,NaN,NaN
1,Igor Gomes,https://s.sde.globo.com/media/person_role/2023...,2.2,4.0,282.0,True,1.0,NaN,2.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,33,NaN,NaN,NaN
2,Pedro Augusto,https://s.sde.globo.com/media/person_role/2023...,1.6,4.0,356.0,True,1.0,3.0,1.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,33,NaN,NaN,NaN
3,Yuri Alberto,https://s.sde.globo.com/media/person_role/2023...,8.3,5.0,264.0,True,NaN,1.0,7.0,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,33,NaN,NaN,NaN
4,Luan Cândido,https://s.sde.globo.com/media/person_role/2022...,2.5,2.0,280.0,True,NaN,NaN,1.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,33,NaN,NaN,NaN

In [21]:
#salvar dado
df1.to_csv('bases/cartola_pontos.csv', index=False,mode='w')

**3.2 Clubes**

Obter codigo do clube.

In [22]:
url= 'https://api.cartola.globo.com/atletas/mercado'
resposta = requests.request("GET", url)
objetos = json.loads(resposta.text)
clubes = pd.json_normalize(objetos['clubes'].values())

In [23]:
#ver dados
display(clubes.head(5))

,nome,abreviacao,slug,apelido,nome_fantasia,id,url_editoria,escudos.60x60,escudos.45x45,escudos.30x30
0,Cuiabá,CUI,cuiaba,Dourado,Cuiabá,1371,https://ge.globo.com/mt/futebol/times/cuiaba/,https://s.sde.globo.com/media/organizations/20...,https://s.sde.globo.com/media/organizations/20...,https://s.sde.globo.com/media/organizations/20...
1,Flamengo,FLA,flamengo,Mengão,Flamengo,262,https://ge.globo.com/futebol/times/flamengo/,https://s.sde.globo.com/media/organizations/20...,https://s.sde.globo.com/media/organizations/20...,https://s.sde.globo.com/media/organizations/20...
2,Botafogo,BOT,botafogo,Glorioso,Botafogo,263,https://ge.globo.com/futebol/times/botafogo/,https://s.sde.globo.com/media/organizations/20...,https://s.sde.globo.com/media/organizations/20...,https://s.sde.globo.com/media/organizations/20...
3,Corinthians,COR,corinthians,Timão,Corinthians,264,https://ge.globo.com/futebol/times/corinthians/,https://s.sde.globo.com/media/organizations/20...,https://s.sde.globo.com/media/organizations/20...,https://s.sde.globo.com/media/organizations/20...
4,Bahia,BAH,bahia,Tricolor de Aço,Bahia,265,https://ge.globo.com/ba/futebol/times/bahia/,https://s.sde.globo.com/media/organizations/20...,https://s.sde.globo.com/media/organizations/20...,https://s.sde.globo.com/media/organizations/20...

In [24]:
#salvar dado
clubes.to_csv('bases/cartola_clubes.csv', index=False,mode='w')

**3.3 Posições**

Obter posiçoes dos jogadores

In [25]:
posicoes = pd.json_normalize(objetos['posicoes'].values())

In [26]:
#salvar dado
posicoes.to_csv('bases/cartola_posicoes.csv', index=False,mode='w')

**3.3 Partidas**

Obter codigo de partidas

In [27]:
#funcao que obtem dado de acordo com a rodada (input)
def GetPartidas(rodada):
 url = 'https://api.cartola.globo.com/partidas/'+str(rodada)
 resposta = requests.get(url)
 objetos = json.loads(resposta.text)
 df = pd.json_normalize(objetos['partidas'])
 df['rodada'] = rodada
 
 return df

In [28]:
#primeira execucao
rodadas = 1
print("Finalizado rodada:",str(rodadas)+ "...")
df1= GetPartidas(1)

#loop para gerar dados, até ultima rodada.
while rodadas != "Erro":
 try:
  rodadas = rodadas+1
  df= GetPartidas(rodadas)
  df1 = df.append(df1)
  print("Finalizado rodada:",str(rodadas)+ "...")
  
 except:
  rodadas = "Erro"
  print("Fim")

Finalizado rodada: 1...
Finalizado rodada: 2...
Finalizado rodada: 3...
Finalizado rodada: 4...
Finalizado rodada: 5...
Finalizado rodada: 6...
Finalizado rodada: 7...
Finalizado rodada: 8...
Finalizado rodada: 9...
Finalizado rodada: 10...
Finalizado rodada: 11...
Finalizado rodada: 12...
Finalizado rodada: 13...
Finalizado rodada: 14...
Finalizado rodada: 15...
Finalizado rodada: 16...
Finalizado rodada: 17...
Finalizado rodada: 18...
Finalizado rodada: 19...
Finalizado rodada: 20...
Finalizado rodada: 21...
Finalizado rodada: 22...
Finalizado rodada: 23...
Finalizado rodada: 24...
Finalizado rodada: 25...
Finalizado rodada: 26...
Finalizado rodada: 27...
Finalizado rodada: 28...
Finalizado rodada: 29...
Finalizado rodada: 30...
Finalizado rodada: 31...
Finalizado rodada: 32...
Finalizado rodada: 33...
Finalizado rodada: 34...
Finalizado rodada: 35...
Finalizado rodada: 36...
Finalizado rodada: 37...
Finalizado rodada: 38...
Fim

In [29]:
#visualizar dados gerados
display(df1.head(5))

,aproveitamento_visitante,aproveitamento_mandante,local,status_transmissao_tr,status_cronometro_tr,periodo_tr,partida_data,inicio_cronometro_tr,placar_oficial_visitante,placar_oficial_mandante,...,clube_visitante_posicao,clube_visitante_id,clube_casa_posicao,clube_casa_id,timestamp,campeonato_id,valida,transmissao.label,transmissao.url,rodada
0,"[, , , , ]","[, , , , ]",,,,,2023-12-03 20:30:00,,None,None,...,0,284,0,266,1701646200,26,True,,,38
1,"[, , , , ]","[, , , , ]",,,,,2023-12-03 20:30:00,,None,None,...,0,280,0,267,1701646200,26,True,,,38
2,"[, , , , ]","[, , , , ]",,,,,2023-12-03 20:30:00,,None,None,...,0,262,0,276,1701646200,26,True,,,38
3,"[, , , , ]","[, , , , ]",,,,,2023-12-03 20:30:00,,None,None,...,0,356,0,277,1701646200,26,True,,,38
4,"[, , , , ]","[, , , , ]",,,,,2023-12-03 20:30:00,,None,None,...,0,327,0,290,1701646200,26,True,,,38

In [30]:
#salvar dado
df1.to_csv('bases/cartola_partidas.csv', index=False,mode='w')